Binary grammars and string literal precedence fix  (#202)
* Add failing test for #201.

* Require a space between a label and string literal.

This prevents parsing r"foo" as a reference to r followed by the literal "foo".
Note this is a breaking change, though a fairly minor one with a simple fix
(add spaces between references and the literal).

* Add failing test asserting that binary grammars work correctly.

* Add support for b"literals", thereby supporting bytestrings.

* Update docstring on `evaluate_string`.

1. the string_escape codec has been removed, and we now use this
   behavior for more than just escaping.
2. add notes about what behavior using ast.literal_eval affords.

* Add validation that all literals are of the same type.

When this validation fails, it looks like this:

>>> Grammar("""
foo = "abc"
bar = b"abc"
""")
[...]
VisitationError: BadGrammar: Found "abc" (<class 'str'>) and b"abc" (<class 'bytes'>) string literals.
All strings in a single grammar must be of the same type.

* Fix invalid escape sequence warning for a grammar in a test file.

* Add documentation about how to use bytes grammars.

* Add release note.

* Update assertions per @ErikRose

Co-authored-by: Lucas Wiman <lucas.wiman@alphahealthai.com>